
- hosts: local
  tasks: 
    - name: check out chat room
      shell: >
        wget https://github.com/baiheng/chat_room/archive/master.zip && 
        unzip -o master.zip && 
        rm /tmp/master.zip 
        chdir=/tmp/
#    - name: start chat room
#      shell: python ./server.py chat_room chdir=/tmp/chat_room-master
